### PR TITLE
Add ability to display the version as a footnote

### PR DESCRIPTION
**Pull request by Tibimac**
I thought this could be an interesting little addition, that's why I added it.
Feel free to make the changes you seem necessary.

### CODE REVIEW

**Comment by SvenTiigi** [comment]
Hi @Tibimac,

Thanks for your PR! 👍 

Adding a footer / footnote below the buttons is a great idea.
However, in my opinion the implementation should be more flexible to support various views, not only a version number, as use cases may vary.

What do you think?

**Comment by Tibimac** [comment]
@SvenTiigi if you have other cases in mind feel free to adjust the implementation for more various cases, now or later. It may be interesting to add this use case now and add more flexibility in a future addition. WDYT ?

**Comment by SvenTiigi** [comment]
Merged in [`feature/footer`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/footer) branch

**Comment by Tibimac** [comment]
Hello @SvenTiigi,
I hope you're fine. Is there any news about the branch [`feature/footer`](https://github.com/SvenTiigi/WhatsNewKit/tree/feature/footer) you created with this PR few months ago ?

**Pull request merged**
