### PR TITLE
Improved macOS design

### PR DESCRIPTION
**Pull request by voltangle**
image
I mostly updated the button design. I removed the custom style and made it native

### CODE REVIEW

**Comment by JulianBissekkou** [comment]
This sounds like a very cool improvement. 
Can we expect this to be merged?

**Comment by JulianBissekkou** [comment]
@SvenTiigi I would like to follow up on this since I am now using this package for my macOS app. 
Any change in getting this merged?

**Comment by SvenTiigi** [comment]
LGTM 👍 Merged!

**Comment by voltangle** [comment]
Wtf how did this take a year omg

**Pull request merged**
